name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Checkout submodules
      run: |
        git submodule sync
        git submodule update --init --recursive
    - name: Update Versions
      env:
        VERSION_PREFIX: 0.14
        VERSION_SUFFIX: ${{github.run_number}}
      run: |
        VERSION=$VERSION_PREFIX.$VERSION_SUFFIX
        sed -i bak "s:<Version>1.0.0</Version>:<Version>$VERSION</Version>:g" Ooui/Ooui.csproj
        sed -i bak "s:<version>1.0.0</version>:<version>$VERSION</version>:g" Ooui.AspNetCore/Ooui.AspNetCore.csproj
        sed -i bak "s:<version>1.0.0</version>:<version>$VERSION</version>:g" Ooui.Forms/Ooui.Forms.csproj
        sed -i bak "s:version=\"1.0.0\":version=\"$VERSION\":g" Ooui.Wasm/Ooui.Wasm.nuspec
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
